//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenGate.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class asignacionordenes
    {
        public int id { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public string Comentarios { get; set; }
        public string AspNetUsers_Id { get; set; }
        public Nullable<int> Concentrado_Id { get; set; }
        public Nullable<int> NomenclaturaDHL_Id { get; set; }
        public Nullable<int> StatusAsignacion_Id { get; set; }
        public int FecuenciaDHL_Id { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual concentrado concentrado { get; set; }
        public virtual fecuenciadhl fecuenciadhl { get; set; }
        public virtual nomenclaturadhl nomenclaturadhl { get; set; }
        public virtual statusasignacion statusasignacion { get; set; }
    }
}
