//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenGate.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class complementosfacturas
    {
        public int id { get; set; }
        public int Bancos_Id { get; set; }
        public int CuentaOrdenante_Id { get; set; }
        public int Factura_Id { get; set; }
        public string Autorizacion { get; set; }
        public int StatusComplemento_Id { get; set; }
        public int Asigancion_Id { get; set; }
    
        public virtual asigancion asigancion { get; set; }
        public virtual bancos bancos { get; set; }
        public virtual cuentaordenante cuentaordenante { get; set; }
        public virtual factura factura { get; set; }
        public virtual statuscomplemento statuscomplemento { get; set; }
    }
}
