//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenGate.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class concentrado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public concentrado()
        {
            this.asignacionordenes = new HashSet<asignacionordenes>();
        }
    
        public int id { get; set; }
        public Nullable<int> NTS_Id { get; set; }
        public Nullable<int> CSR_Id { get; set; }

        public Nullable<int>GuiasImpresas_Id { get; set; }

        public virtual csr csr { get; set; }
        public virtual guiasimpresas guiasimpresas { get; set; }
        public virtual nts nts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<asignacionordenes> asignacionordenes { get; set; }
    }
}
