//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenGate.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class csr
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public csr()
        {
            this.concentrado = new HashSet<concentrado>();
        }
    
        public int id { get; set; }
        public string NumeroCuenta { get; set; }
        public string Guia { get; set; }
        public string PieceID { get; set; }
        public string Referencia { get; set; }
        public string IATAOrigen { get; set; }
        public string CiudadOrigen { get; set; }
        public string IATADestino { get; set; }
        public string CiudadDestino { get; set; }
        public string SVCSubIATA { get; set; }
        public string Ruta { get; set; }
        public Nullable<int> Piezas { get; set; }
        public Nullable<decimal> Peso { get; set; }
        public Nullable<System.DateTime> FechaRecoleccion { get; set; }
        public Nullable<System.DateTime> FechaPrimerCheckpointTerminal { get; set; }
        public string HoraPrimerCheckpointTerminal { get; set; }
        public string PrimerCheckpointTerminal { get; set; }
        public string DescripcionPrimerCheckTerminal { get; set; }
        public string DetallesEntregaComentarios { get; set; }
        public Nullable<int> TiempoTransitoEstimado { get; set; }
        public Nullable<int> TiempoTransitoRealizado { get; set; }
        public Nullable<int> IntentosEntrega { get; set; }
        public string CausaDemora { get; set; }
        public Nullable<System.DateTime> FechaIngresoCC { get; set; }
        public Nullable<int> DiasCC { get; set; }
        public string Producto { get; set; }
        public Nullable<decimal> ValorSeguro { get; set; }
        public string NombreRemitente { get; set; }
        public string ContactoRemitente { get; set; }
        public string DireccionRemitente { get; set; }
        public string CPRemitente { get; set; }
        public string NombreDestinatario { get; set; }
        public string ContactoDestinatario { get; set; }
        public string DireccionDestinatario { get; set; }
        public string CPDestinatario { get; set; }
        public string UltimoCheckpoint { get; set; }
        public Nullable<System.DateTime> FechaUltimoCheckpoint { get; set; }
        public string HoraUltimoCheckpoint { get; set; }
        public string detalleultimocheckpoint { get; set; }
        public Nullable<System.DateTime> FechaCarga { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<concentrado> concentrado { get; set; }
    }
}
