//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenGate.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class empleado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public empleado()
        {
            this.equiposcomputo = new HashSet<equiposcomputo>();
        }
    
        public int id { get; set; }
        public string Nombre { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public string Direccion { get; set; }
        public int Puesto_Id { get; set; }
        public int Area_Id { get; set; }
        public string AspNetUsers_Id { get; set; }
        public byte[] foto { get; set; }
        public string NameFile { get; set; }
        public string ExtFile { get; set; }
        public string Celular { get; set; }
        public string Telefono { get; set; }
    
        public virtual area area { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual puesto puesto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<equiposcomputo> equiposcomputo { get; set; }
    }
}
