//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenGate.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class envioshomedelivery
    {
        public int id { get; set; }
        public string tipoenvio { get; set; }
        public string solicitante { get; set; }
        public string mes { get; set; }
        public Nullable<System.DateTime> fecharequerimiento { get; set; }
        public string sku { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> cantidad { get; set; }
        public string cv { get; set; }
        public string destino { get; set; }
        public Nullable<int> cajas { get; set; }
        public string paqueteria { get; set; }
        public string referenciaguia { get; set; }
        public string numeroguia { get; set; }
        public string numerorequerimiento { get; set; }
        public string tiposalida { get; set; }
        public string aplicacion { get; set; }
        public string observaciones { get; set; }
    }
}
