//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenGate.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class equiposcomputo
    {
        public int id { get; set; }
        public string CPU { get; set; }
        public Nullable<int> RAM { get; set; }
        public string SistemaOperativo { get; set; }
        public string NombreEquipo { get; set; }
        public string Modelo { get; set; }
        public string Marca { get; set; }
        public string TipoEquipo { get; set; }
        public string Ubicacion { get; set; }
        public string ServiceTag { get; set; }
        public string ExpressServiceCode { get; set; }
        public Nullable<System.DateTime> FechaEntrada { get; set; }
        public Nullable<int> FechaBaja { get; set; }
        public int Empleado_Id { get; set; }
        public int EquipoMantenimiento_Id { get; set; }
        public string HDD { get; set; }
    
        public virtual empleado empleado { get; set; }
        public virtual equipomantenimiento equipomantenimiento { get; set; }
    }
}
