//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenGate.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class factura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public factura()
        {
            this.pagofacturas = new HashSet<pagofacturas>();
            this.complementosfacturas = new HashSet<complementosfacturas>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public string Numero { get; set; }
        public Nullable<System.DateTime> FechaFactura { get; set; }
        public Nullable<System.DateTime> FechaSello { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
        public Nullable<System.DateTime> FechaPago { get; set; }
        public string Concepto { get; set; }
        public Nullable<decimal> Subtotal { get; set; }
        public Nullable<decimal> Iva { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public Nullable<decimal> Retencion { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string Observaciones { get; set; }
        public int Proveedor_Id { get; set; }
        public int StatusFactura_Id { get; set; }
        public string AspNetUsers_Id { get; set; }
        public int Clientes_Id { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual clientes clientes { get; set; }
        public virtual statusfactura statusfactura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pagofacturas> pagofacturas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<complementosfacturas> complementosfacturas { get; set; }
        public virtual proveedor proveedor { get; set; }
    }
}
