//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenGate.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class fecuenciadhl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public fecuenciadhl()
        {
            this.asignacionordenes = new HashSet<asignacionordenes>();
        }
    
        public int id { get; set; }
        public string carrier { get; set; }
        public string postalcode { get; set; }
        public string freightcode { get; set; }
        public Nullable<int> frequency { get; set; }
        public string wharehouse { get; set; }
        public string statusfq { get; set; }
        public string descripcion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<asignacionordenes> asignacionordenes { get; set; }
    }
}
