//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenGate.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class kpisinventariosaplontime
    {
        public int id { get; set; }
        public string Mes { get; set; }
        public Nullable<System.DateTime> FechaReciboFisico { get; set; }
        public Nullable<System.DateTime> FechaTerminoValidacion { get; set; }
        public Nullable<int> DiasValidacion { get; set; }
        public Nullable<System.DateTime> FechaCreacionOracle { get; set; }
        public Nullable<System.DateTime> FechaReciboOracle { get; set; }
        public Nullable<int> DiasOracle { get; set; }
        public string FolioFacturacion { get; set; }
        public string Observaciones { get; set; }
        public string CV { get; set; }
        public string Number { get; set; }
        public string ordernumber { get; set; }
        public Nullable<int> piezassistema { get; set; }
        public Nullable<int> piezasfisico { get; set; }
        public Nullable<int> palletsrecibidos { get; set; }
        public Nullable<decimal> montofacturado { get; set; }
        public string ingresado { get; set; }
    }
}
