//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenGate.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class kpisplaneacion
    {
        public int id { get; set; }
        public string mes { get; set; }
        public string ano { get; set; }
        public Nullable<System.DateTime> fechaembarque { get; set; }
        public Nullable<int> wk { get; set; }
        public string cv { get; set; }
        public string mo { get; set; }
        public string subinventario { get; set; }
        public string requisicion { get; set; }
        public string orden { get; set; }
        public string aplicacion { get; set; }
        public Nullable<System.DateTime> fechageneracion { get; set; }
        public Nullable<System.DateTime> fechaentrega { get; set; }
        public string tipoembarque { get; set; }
        public string status { get; set; }
    }
}
