//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenGate.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class kpisinventariosexactitud
    {
        public int id { get; set; }
        public string subinventario { get; set; }
        public string mes { get; set; }
        public Nullable<decimal> absoluto { get; set; }
        public Nullable<decimal> valorinventario { get; set; }
    }
}
