//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenGate.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class kpisdespacho
    {
        public int id { get; set; }
        public Nullable<int> diasemana { get; set; }
        public Nullable<int> wk { get; set; }
        public string mes { get; set; }
        public string cv { get; set; }
        public string mo { get; set; }
        public string tipoembarque { get; set; }
        public Nullable<System.DateTime> fechaembarque { get; set; }
        public Nullable<int> qtypiezas { get; set; }
        public Nullable<int> qtycajas { get; set; }
        public Nullable<decimal> qtypallets { get; set; }
        public Nullable<int> valordia { get; set; }
    }
}
