//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenGate.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class kpisinvetntarios
    {
        public int id { get; set; }
        public string skuvariance { get; set; }
        public Nullable<int> monto { get; set; }
        public Nullable<decimal> porcentajemonto { get; set; }
        public Nullable<int> piezas { get; set; }
        public Nullable<decimal> porcentajepiezas { get; set; }
        public string mes { get; set; }
        public string area { get; set; }
    }
}
