//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenGate.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class kpistrafico
    {
        public int id { get; set; }
        public string remision { get; set; }
        public string consecutivoflete { get; set; }
        public string respnsableflete { get; set; }
        public string mescarga { get; set; }
        public string origen { get; set; }
        public string destino { get; set; }
        public string wh { get; set; }
        public string ruta { get; set; }
        public string tiporequerimiento { get; set; }
        public Nullable<int> wk { get; set; }
        public Nullable<System.DateTime> fechacarga { get; set; }
        public Nullable<System.DateTime> fechaentrega { get; set; }
        public string ro { get; set; }
        public string tipoenvio { get; set; }
        public string tipounidad { get; set; }
        public Nullable<decimal> capasidadpalletsunidad { get; set; }
        public Nullable<decimal> palletsembarcados { get; set; }
        public Nullable<decimal> porcentajeocupacionunidad { get; set; }
        public Nullable<decimal> capasidadunidad { get; set; }
        public Nullable<decimal> pesoinventario { get; set; }
        public Nullable<decimal> porcentajepesounidad { get; set; }
        public string evaluacionocupacionunidad { get; set; }
        public Nullable<int> numerocajas { get; set; }
        public Nullable<int> numeropiezas { get; set; }
        public Nullable<decimal> costoflete { get; set; }
        public Nullable<decimal> costomaniobras { get; set; }
        public Nullable<System.DateTime> fhrequeridaposicionamiento { get; set; }
        public Nullable<System.DateTime> fhrealpsocicionamiento { get; set; }
        public string evaluacionposicionamiento { get; set; }
        public Nullable<System.DateTime> fhcita { get; set; }
        public Nullable<System.DateTime> fharriboreal { get; set; }
        public string evaluacionentrega { get; set; }
        public Nullable<int> maniobristasrequeridos { get; set; }
        public Nullable<int> maniobristasatiempo { get; set; }
        public string evaluacionmaniobras { get; set; }
        public string observaciones { get; set; }
    }
}
