//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenGate.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class kpisrecibo
    {
        public int id { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> wk { get; set; }
        public string mes { get; set; }
        public string proveedor { get; set; }
        public string ordenguia { get; set; }
        public string descarga { get; set; }
        public Nullable<System.DateTime> fechahoradescarga { get; set; }
        public Nullable<System.DateTime> fechahoraingresosistema { get; set; }
        public string tiempoaplicacionoracle { get; set; }
        public string evaluacioningreso { get; set; }
    }
}
