//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenGate.Entidades
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbOpenGateLogisticsEntities : DbContext
    {
        public dbOpenGateLogisticsEntities()
            : base("name=dbOpenGateLogisticsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<bancos> bancos { get; set; }
        public virtual DbSet<categoriaproveedor> categoriaproveedor { get; set; }
        public virtual DbSet<clientes> clientes { get; set; }
        public virtual DbSet<cuentaordenante> cuentaordenante { get; set; }
        public virtual DbSet<factura> factura { get; set; }
        public virtual DbSet<nacionalidadproveedor> nacionalidadproveedor { get; set; }
        public virtual DbSet<pago> pago { get; set; }
        public virtual DbSet<pagofacturas> pagofacturas { get; set; }
        public virtual DbSet<statusfactura> statusfactura { get; set; }
        public virtual DbSet<statuspago> statuspago { get; set; }
        public virtual DbSet<asigancion> asigancion { get; set; }
        public virtual DbSet<complementosfacturas> complementosfacturas { get; set; }
        public virtual DbSet<statuscomplemento> statuscomplemento { get; set; }
        public virtual DbSet<statustarea> statustarea { get; set; }
        public virtual DbSet<kpisplaneacion> kpisplaneacion { get; set; }
        public virtual DbSet<tareas> tareas { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<kpisdespacho> kpisdespacho { get; set; }
        public virtual DbSet<kpisrecibo> kpisrecibo { get; set; }
        public virtual DbSet<kpisinvetntarios> kpisinvetntarios { get; set; }
        public virtual DbSet<kpisinventariosaplontime> kpisinventariosaplontime { get; set; }
        public virtual DbSet<kpisinventariosexactitud> kpisinventariosexactitud { get; set; }
        public virtual DbSet<servicios> servicios { get; set; }
        public virtual DbSet<kpistrafico> kpistrafico { get; set; }
        public virtual DbSet<area> area { get; set; }
        public virtual DbSet<puesto> puesto { get; set; }
        public virtual DbSet<empleado> empleado { get; set; }
        public virtual DbSet<envioshomedelivery> envioshomedelivery { get; set; }
        public virtual DbSet<equipomantenimiento> equipomantenimiento { get; set; }
        public virtual DbSet<equiposcomputo> equiposcomputo { get; set; }
        public virtual DbSet<mo> mo { get; set; }
        public virtual DbSet<statusproveedor> statusproveedor { get; set; }
        public virtual DbSet<statusproveedorvisible> statusproveedorvisible { get; set; }
        public virtual DbSet<contactoproveedor> contactoproveedor { get; set; }
        public virtual DbSet<informacionbancaria> informacionbancaria { get; set; }
        public virtual DbSet<proveedor> proveedor { get; set; }
        public virtual DbSet<centrocostos> centrocostos { get; set; }
        public virtual DbSet<statuscompras> statuscompras { get; set; }
        public virtual DbSet<statusdireccion> statusdireccion { get; set; }
        public virtual DbSet<statusfinanzas> statusfinanzas { get; set; }
        public virtual DbSet<subcentrocostos> subcentrocostos { get; set; }
        public virtual DbSet<categoriaorden> categoriaorden { get; set; }
        public virtual DbSet<tipocompra> tipocompra { get; set; }
        public virtual DbSet<productos> productos { get; set; }
        public virtual DbSet<detalleordenproductos> detalleordenproductos { get; set; }
        public virtual DbSet<formapago> formapago { get; set; }
        public virtual DbSet<supervisor> supervisor { get; set; }
        public virtual DbSet<solicitante> solicitante { get; set; }
        public virtual DbSet<ordencompra> ordencompra { get; set; }
        public virtual DbSet<csr> csr { get; set; }
        public virtual DbSet<nts> nts { get; set; }
        public virtual DbSet<guiasimpresas> guiasimpresas { get; set; }
        public virtual DbSet<fecuenciadhl> fecuenciadhl { get; set; }
        public virtual DbSet<nomenclaturadhl> nomenclaturadhl { get; set; }
        public virtual DbSet<statusasignacion> statusasignacion { get; set; }
        public virtual DbSet<concentrado> concentrado { get; set; }
        public virtual DbSet<asignacionordenes> asignacionordenes { get; set; }
        public virtual DbSet<skus> skus { get; set; }
        public virtual DbSet<detkitskus> detkitskus { get; set; }
        public virtual DbSet<detordenproductoshd> detordenproductoshd { get; set; }
        public virtual DbSet<detusuariosordenes> detusuariosordenes { get; set; }
        public virtual DbSet<erroresordenes> erroresordenes { get; set; }
        public virtual DbSet<guias> guias { get; set; }
        public virtual DbSet<kit> kit { get; set; }
        public virtual DbSet<ordenes> ordenes { get; set; }
        public virtual DbSet<usuarios> usuarios { get; set; }
        public virtual DbSet<codigoqrordenes> codigoqrordenes { get; set; }
        public virtual DbSet<statusordenimpresa> statusordenimpresa { get; set; }
        public virtual DbSet<tipoerror> tipoerror { get; set; }
    }
}
