//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenGate.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class nts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public nts()
        {
            this.concentrado = new HashSet<concentrado>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> NTSDate { get; set; }
        public string Order { get; set; }
        public string DSIdCliente { get; set; }
        public string DSNombreCliente { get; set; }
        public string OSACalleNumero { get; set; }
        public string OSANull1 { get; set; }
        public string OSAColonia { get; set; }
        public string OSADestinatario { get; set; }
        public string OSACiudad { get; set; }
        public string OSANull2 { get; set; }
        public string OSAEstado { get; set; }
        public string OSACodigoPostal { get; set; }
        public string OSI { get; set; }
        public string osp { get; set; }
        public string osh { get; set; }
        public string ofcodigopais { get; set; }
        public string oforigen { get; set; }
        public Nullable<System.DateTime> fecharegistro { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<concentrado> concentrado { get; set; }
    }
}
