//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenGate.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class ordenes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ordenes()
        {
            this.detordenproductoshd = new HashSet<detordenproductoshd>();
            this.detusuariosordenes = new HashSet<detusuariosordenes>();
            this.erroresordenes = new HashSet<erroresordenes>();
            this.guias = new HashSet<guias>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public string Orden { get; set; }
        public string User { get; set; }
        public int StatusOrdenImpresa_Id { get; set; }
        public string Picker { get; set; }

        public int Cantidad { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detordenproductoshd> detordenproductoshd { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detusuariosordenes> detusuariosordenes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<erroresordenes> erroresordenes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<guias> guias { get; set; }
    }
}
