//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenGate.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class proveedor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public proveedor()
        {
            this.contactoproveedor = new HashSet<contactoproveedor>();
            this.factura = new HashSet<factura>();
            this.informacionbancaria = new HashSet<informacionbancaria>();
            this.ordencompra = new HashSet<ordencompra>();
        }
    
        public int id { get; set; }
        public string RazonSocial { get; set; }
        public string RFC { get; set; }
        public int NacionalidadProveedor_Id { get; set; }
        public int CategoriaProveedor_Id { get; set; }
        public int StatusProveedor_Id { get; set; }
        public Nullable<int> StatusProveedorVisible_Id { get; set; }
        public string Pais { get; set; }
        public string Estado { get; set; }
        public string Municipio { get; set; }
        public string Calle { get; set; }
        public string CodigoPostal { get; set; }
        public string ModenaFacturacion { get; set; }
        public Nullable<int> DiasCredito { get; set; }
        public string RepresentanteLegal { get; set; }
        public string ActividadEmpresarial { get; set; }
        public string NombreComercial { get; set; }
        public string Colonia { get; set; }
    
        public virtual categoriaproveedor categoriaproveedor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<contactoproveedor> contactoproveedor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<factura> factura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<informacionbancaria> informacionbancaria { get; set; }
        public virtual nacionalidadproveedor nacionalidadproveedor { get; set; }
        public virtual statusproveedor statusproveedor { get; set; }
        public virtual statusproveedorvisible statusproveedorvisible { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ordencompra> ordencompra { get; set; }
    }
}
