//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenGate.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tareas
    {
        public int id { get; set; }
        public string Actividad { get; set; }
        public string HoraInicio { get; set; }
        public string Solicita { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.DateTime> FechaEntrega { get; set; }
        public string HoraFin { get; set; }
        public Nullable<int> PorcentajeCumplido { get; set; }
        public string Observaciones { get; set; }
        public string Notas { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public int StatusTarea_Id { get; set; }
        public string AspNetUsers_Id { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual statustarea statustarea { get; set; }
    }
}
